### ISSUE TITLE
Should allow quoted keys

### ISSUE THREAD

**Issue by plambert** [ddiachkov/sublime-yaml-nav#13]
Given:

``` yaml

---
foo.bar:
  'baz':
    lemur: "weasel"
```

The list of keys given with super-R is:
foo.bar
foo.bar.lemur

The same is true with a double-quoted key name.

The entity.name.tag.yaml scope should apply to 'baz': as well as the others.

Thanks!
